let resume={
    name : " Sudharsanan" ,
    Fathersname : "Murugesan",
    Age:27,
    Education:[
        {
            Standard:"10th",
            Institute:"BVHS",
            place : "Kulithalai",
            Percentage:"86%"
        },
        {
            Standard:"12th",
            Institute:"SSMHSS",
            place :"Petavaithalai",
            Percentage:"62%"
        },
        {
            Degree:"BE",
            Branch:"Mechanical",
            Institute : "Oxford Engineering College",
            place : "Trichy" ,
            Percentage : "68%"
        }
    ],
    Hobbies:["yoga","playing","roaming"],

};
console.log(resume.Education[1]. place )
console.log(resume.Education[2].Degree)
console.log(resume.Education[2].Branch)



// Petavaithalai
// BE
//  Mechanical